# Settings for game objects

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

PLAYER_MOVEMENT_SPEED = 200
PLAYER_RADIUS = 16
PLAYER_SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOT_COOLDOWN = 0.3
PLAYER_TURN_SPEED = 300

ASTEROID_KINDS = 3
ASTEROID_MIN_RADIUS = 20
ASTEROID_SPAWN_RATE = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
